#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_ssn_h.py
============
读取描述 NT 函数 syscall 号(SSN) 的 JSON 文件，为每个函数生成
SSN/<FuncName>.h。每个头文件包含：
  - 每个版本/SP 一条 #define SYSCALL_<Func>_<Ver>  <ssn>
  - 一个 static __inline unsigned long SsnForBuild(unsigned long dwBuildNumber)
    根据当前系统 NT build 号返回对应 SSN（switch 分发）

JSON 格式:
{
  "NtAdjustPrivilegesToken": {
    "Windows XP":              { "SP1": 62, "SP2": 62 },
    "Windows Server 2003":     { "SP0": 62, "SP2": 62, "R2": 62, "R2 SP2": 62 },
    "Windows Vista":           { "SP0": 62, "SP1": 62, "SP2": 62 },
    "Windows 7":               { "SP0": 62, "SP1": 62 },
    "Windows 8":               { "8.0": 63, "8.1": 64 },
    "Windows 10":              { "1507": 65, ..., "22H2": 65 },
    "Windows 11 and Server":   { "Server 2022": 65, "11 21H2": 65, ... }
  }
}

build 号映射策略：
  对每个 (版本组, 子项) 计算一个 NT build 号。旧版本按版本+SP 查表；
  Win10/Win11/Server 按版本标识（1507/20H2/21H2/24H2...）查表。
  同一 build 号只保留首个出现的 case（去重），值以最后写入为准（高版本优先）。
"""

import json
import os
import re
import argparse


# ----------------------------------------------------------------------
# NT build 号映射表
# ----------------------------------------------------------------------

# 旧版 Windows：按 "版本组key -> { sp子项key -> build }"
LEGACY_BUILD = {
    "Windows XP": {
        "SP0": 2600, "SP1": 2600, "SP2": 2600, "SP3": 2600,
    },
    "Windows Server 2003": {
        "SP0": 3790, "SP1": 3790, "SP2": 3790,
        "R2": 3790, "R2 SP2": 3790,
    },
    "Windows Vista": {
        "SP0": 6000, "SP1": 6001, "SP2": 6002,
    },
    "Windows 7": {
        "SP0": 7600, "SP1": 7601,
    },
    "Windows 8": {
        "8.0": 9200, "8.1": 9600,
    },
}

# Win10/11/Server 按版本标识（子项 key）查 build 号
MODERN_BUILD = {
    # Windows 10
    "1507": 10240, "1511": 10586, "1607": 14393, "1703": 15063,
    "1709": 16299, "1803": 17134, "1809": 17763, "1903": 18362,
    "1909": 18363, "2004": 19041, "20H2": 19042, "21H1": 19043,
    "21H2": 19044, "22H2": 19045,
    # Windows 11
    "11 21H2": 22000, "11 22H2": 22621, "11 23H2": 22631,
    "11 24H2": 26100, "11 25H2": 26200,
    # Server
    "Server 2022": 20348, "Server 2025": 26100, "Server 23H2": 25398,
}


HEADER = """/* Auto-generated by gen_ssn_h.py -- do not edit by hand. */
#pragma once

{define_block}

/*
 * 根据当前系统 NT build 号返回 {func} 的 syscall 号。
 * 用法: unsigned long ssn = SsnForBuild_{func}(KUtils::GetSystemBuildNumber());
 */
static __inline unsigned long SsnForBuild_{func}(unsigned long dwBuildNumber)
{{
    switch (dwBuildNumber)
    {{
{cases}
        default: return {default_ssn};
    }}
}}
"""


def sanitize(name):
    name = name.replace("Windows ", "Win").replace("Server ", "Server")
    name = name.replace(" and ", "_").replace(" & ", "_")
    name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
    return name


def build_for(ver, sp):
    """返回 (build号, 注释) 或 (None, None)"""
    # 旧版查表
    if ver in LEGACY_BUILD:
        d = LEGACY_BUILD[ver]
        # 精确匹配子项
        if sp in d:
            return d[sp], f"{ver} {sp}"
        # 兜底：取该版本首个 build
        first_sp = next(iter(d))
        return d[first_sp], f"{ver} {first_sp}"
    # 现代版查表（子项即版本标识）
    if sp in MODERN_BUILD:
        return MODERN_BUILD[sp], f"{ver} {sp}"
    return None, None


def gen_header(func, data):
    defines = []
    case_map = {}  # build -> (ssn, comment)

    for ver, sps in data.items():
        for sp, ssn in sps.items():
            # --- define 宏后缀 ---
            if ver == "Windows 11 and Server":
                # 子项自身已含 "11 xx" / "Server xx"，直接用它
                macro_suffix = sanitize(sp)
            else:
                suffix = sanitize(ver)
                sp_part = sanitize(sp)
                if suffix and sp_part:
                    macro_suffix = f"{suffix}_{sp_part}"
                elif sp_part:
                    macro_suffix = sp_part
                else:
                    macro_suffix = suffix
            defines.append(f"#define SYSCALL_{func}_{macro_suffix}  {ssn}")

            # --- case 语句 ---
            build, comment = build_for(ver, sp)
            if build is None:
                continue
            # 同一 build 号：高版本（后遍历到）覆盖前值
            case_map[build] = (ssn, comment)

    defines.sort()

    # 按 build 号升序生成 case
    cases = []
    for build in sorted(case_map.keys()):
        ssn, comment = case_map[build]
        cases.append(f"        case {build}: return {ssn}; /* {comment} */")

    # 默认值：取最大 build 号对应的值（最新系统）
    default_ssn = 0
    if case_map:
        last_build = max(case_map.keys())
        default_ssn = case_map[last_build][0]

    return HEADER.format(
        func=func,
        define_block="\n".join(defines),
        cases="\n".join(cases),
        default_ssn=default_ssn,
    )


# 可选：只生成这些函数（为空则生成全部）
ONLY_FUNCS = ["NtAdjustPrivilegesToken", "NtInitiatePowerAction"]


def main():
    ap = argparse.ArgumentParser(description="Generate SSN/<FuncName>.h from JSON.")
    ap.add_argument("-j", "--json", default="syscall-data/nt-per-syscall.json", help="JSON Path")
    ap.add_argument("-o", "--out", default="InfinityHookPro/ssn", help="out dir")
    args = ap.parse_args()

    with open(args.json, "r", encoding="utf-8") as f:
        root = json.load(f)

    os.makedirs(args.out, exist_ok=True)
    for func, data in root.items():
        if ONLY_FUNCS and func not in ONLY_FUNCS:
            continue
        hdr = gen_header(func, data)
        path = os.path.join(args.out, f"{func}.h")
        with open(path, "w", encoding="utf-8") as f:
            f.write(hdr)
        print(f"[+] {path}")


if __name__ == "__main__":
    main()