/* Auto-generated by gen_ssn_h.py -- do not edit by hand. */
#pragma once

#define SYSCALL_NtAdjustPrivilegesToken_11_21H2  65
#define SYSCALL_NtAdjustPrivilegesToken_11_22H2  65
#define SYSCALL_NtAdjustPrivilegesToken_11_23H2  65
#define SYSCALL_NtAdjustPrivilegesToken_11_24H2  65
#define SYSCALL_NtAdjustPrivilegesToken_11_25H2  65
#define SYSCALL_NtAdjustPrivilegesToken_Server2022  65
#define SYSCALL_NtAdjustPrivilegesToken_Server2025  65
#define SYSCALL_NtAdjustPrivilegesToken_Server23H2  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1507  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1511  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1607  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1703  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1709  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1803  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1809  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1903  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_1909  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_2004  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_20H2  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_21H1  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_21H2  65
#define SYSCALL_NtAdjustPrivilegesToken_Win10_22H2  65
#define SYSCALL_NtAdjustPrivilegesToken_Win7_SP0  62
#define SYSCALL_NtAdjustPrivilegesToken_Win7_SP1  62
#define SYSCALL_NtAdjustPrivilegesToken_Win8_8_0  63
#define SYSCALL_NtAdjustPrivilegesToken_Win8_8_1  64
#define SYSCALL_NtAdjustPrivilegesToken_WinServer2003_R2  62
#define SYSCALL_NtAdjustPrivilegesToken_WinServer2003_R2_SP2  62
#define SYSCALL_NtAdjustPrivilegesToken_WinServer2003_SP0  62
#define SYSCALL_NtAdjustPrivilegesToken_WinServer2003_SP2  62
#define SYSCALL_NtAdjustPrivilegesToken_WinVista_SP0  62
#define SYSCALL_NtAdjustPrivilegesToken_WinVista_SP1  62
#define SYSCALL_NtAdjustPrivilegesToken_WinVista_SP2  62
#define SYSCALL_NtAdjustPrivilegesToken_WinXP_SP1  62
#define SYSCALL_NtAdjustPrivilegesToken_WinXP_SP2  62

/*
 * 根据当前系统 NT build 号返回 NtAdjustPrivilegesToken 的 syscall 号。
 * 用法: unsigned long ssn = SsnForBuild_NtAdjustPrivilegesToken(KUtils::GetSystemBuildNumber());
 */
static __inline unsigned long SsnForBuild_NtAdjustPrivilegesToken(unsigned long dwBuildNumber)
{
    switch (dwBuildNumber)
    {
        case 2600: return 62; /* Windows XP SP2 */
        case 3790: return 62; /* Windows Server 2003 R2 SP2 */
        case 6000: return 62; /* Windows Vista SP0 */
        case 6001: return 62; /* Windows Vista SP1 */
        case 6002: return 62; /* Windows Vista SP2 */
        case 7600: return 62; /* Windows 7 SP0 */
        case 7601: return 62; /* Windows 7 SP1 */
        case 9200: return 63; /* Windows 8 8.0 */
        case 9600: return 64; /* Windows 8 8.1 */
        case 10240: return 65; /* Windows 10 1507 */
        case 10586: return 65; /* Windows 10 1511 */
        case 14393: return 65; /* Windows 10 1607 */
        case 15063: return 65; /* Windows 10 1703 */
        case 16299: return 65; /* Windows 10 1709 */
        case 17134: return 65; /* Windows 10 1803 */
        case 17763: return 65; /* Windows 10 1809 */
        case 18362: return 65; /* Windows 10 1903 */
        case 18363: return 65; /* Windows 10 1909 */
        case 19041: return 65; /* Windows 10 2004 */
        case 19042: return 65; /* Windows 10 20H2 */
        case 19043: return 65; /* Windows 10 21H1 */
        case 19044: return 65; /* Windows 10 21H2 */
        case 19045: return 65; /* Windows 10 22H2 */
        case 20348: return 65; /* Windows 11 and Server Server 2022 */
        case 22000: return 65; /* Windows 11 and Server 11 21H2 */
        case 22621: return 65; /* Windows 11 and Server 11 22H2 */
        case 22631: return 65; /* Windows 11 and Server 11 23H2 */
        case 25398: return 65; /* Windows 11 and Server Server 23H2 */
        case 26100: return 65; /* Windows 11 and Server Server 2025 */
        case 26200: return 65; /* Windows 11 and Server 11 25H2 */
        default: return 65;
    }
}
