/* Auto-generated by gen_ssn_h.py -- do not edit by hand. */
#pragma once

#define SYSCALL_NtInitiatePowerAction_11_21H2  263
#define SYSCALL_NtInitiatePowerAction_11_22H2  264
#define SYSCALL_NtInitiatePowerAction_11_23H2  264
#define SYSCALL_NtInitiatePowerAction_11_24H2  266
#define SYSCALL_NtInitiatePowerAction_11_25H2  266
#define SYSCALL_NtInitiatePowerAction_Server2022  262
#define SYSCALL_NtInitiatePowerAction_Server2025  266
#define SYSCALL_NtInitiatePowerAction_Server23H2  265
#define SYSCALL_NtInitiatePowerAction_Win10_1507  241
#define SYSCALL_NtInitiatePowerAction_Win10_1511  243
#define SYSCALL_NtInitiatePowerAction_Win10_1607  245
#define SYSCALL_NtInitiatePowerAction_Win10_1703  248
#define SYSCALL_NtInitiatePowerAction_Win10_1709  249
#define SYSCALL_NtInitiatePowerAction_Win10_1803  250
#define SYSCALL_NtInitiatePowerAction_Win10_1809  251
#define SYSCALL_NtInitiatePowerAction_Win10_1903  252
#define SYSCALL_NtInitiatePowerAction_Win10_1909  252
#define SYSCALL_NtInitiatePowerAction_Win10_2004  257
#define SYSCALL_NtInitiatePowerAction_Win10_20H2  257
#define SYSCALL_NtInitiatePowerAction_Win10_21H1  257
#define SYSCALL_NtInitiatePowerAction_Win10_21H2  258
#define SYSCALL_NtInitiatePowerAction_Win10_22H2  258
#define SYSCALL_NtInitiatePowerAction_Win7_SP0  216
#define SYSCALL_NtInitiatePowerAction_Win7_SP1  216
#define SYSCALL_NtInitiatePowerAction_Win8_8_0  234
#define SYSCALL_NtInitiatePowerAction_Win8_8_1  237
#define SYSCALL_NtInitiatePowerAction_WinServer2003_R2  165
#define SYSCALL_NtInitiatePowerAction_WinServer2003_R2_SP2  165
#define SYSCALL_NtInitiatePowerAction_WinServer2003_SP0  165
#define SYSCALL_NtInitiatePowerAction_WinServer2003_SP2  165
#define SYSCALL_NtInitiatePowerAction_WinVista_SP0  215
#define SYSCALL_NtInitiatePowerAction_WinVista_SP1  213
#define SYSCALL_NtInitiatePowerAction_WinVista_SP2  213
#define SYSCALL_NtInitiatePowerAction_WinXP_SP1  165
#define SYSCALL_NtInitiatePowerAction_WinXP_SP2  165

/*
 * 根据当前系统 NT build 号返回 NtInitiatePowerAction 的 syscall 号。
 * 用法: unsigned long ssn = SsnForBuild_NtInitiatePowerAction(KUtils::GetSystemBuildNumber());
 */
static __inline unsigned long SsnForBuild_NtInitiatePowerAction(unsigned long dwBuildNumber)
{
    switch (dwBuildNumber)
    {
        case 2600: return 165; /* Windows XP SP2 */
        case 3790: return 165; /* Windows Server 2003 R2 SP2 */
        case 6000: return 215; /* Windows Vista SP0 */
        case 6001: return 213; /* Windows Vista SP1 */
        case 6002: return 213; /* Windows Vista SP2 */
        case 7600: return 216; /* Windows 7 SP0 */
        case 7601: return 216; /* Windows 7 SP1 */
        case 9200: return 234; /* Windows 8 8.0 */
        case 9600: return 237; /* Windows 8 8.1 */
        case 10240: return 241; /* Windows 10 1507 */
        case 10586: return 243; /* Windows 10 1511 */
        case 14393: return 245; /* Windows 10 1607 */
        case 15063: return 248; /* Windows 10 1703 */
        case 16299: return 249; /* Windows 10 1709 */
        case 17134: return 250; /* Windows 10 1803 */
        case 17763: return 251; /* Windows 10 1809 */
        case 18362: return 252; /* Windows 10 1903 */
        case 18363: return 252; /* Windows 10 1909 */
        case 19041: return 257; /* Windows 10 2004 */
        case 19042: return 257; /* Windows 10 20H2 */
        case 19043: return 257; /* Windows 10 21H1 */
        case 19044: return 258; /* Windows 10 21H2 */
        case 19045: return 258; /* Windows 10 22H2 */
        case 20348: return 262; /* Windows 11 and Server Server 2022 */
        case 22000: return 263; /* Windows 11 and Server 11 21H2 */
        case 22621: return 264; /* Windows 11 and Server 11 22H2 */
        case 22631: return 264; /* Windows 11 and Server 11 23H2 */
        case 25398: return 265; /* Windows 11 and Server Server 23H2 */
        case 26100: return 266; /* Windows 11 and Server Server 2025 */
        case 26200: return 266; /* Windows 11 and Server 11 25H2 */
        default: return 266;
    }
}
